security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            lazy: true
            provider: app_user_provider
            stateless: false
            context: shared_context
            entry_point: App\Security\JsonAuthenticationEntryPoint
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\FormAuthenticator
            entry_point: App\Security\FormAuthenticator
            context: shared_context
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
