name: symfony-react-starter
type: symfony
docroot: public
php_version: "8.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: postgres
    version: "17"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
host_db_port: "51200"
